/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practicetask;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.springframework.context.ApplicationContext;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class AppTest {

    @Autowired
    ApplicationContext context;

    @Test
    void contextLoads(ApplicationContext context) {
        assertNotNull(context);
    }
}
