services:
  provider-service:
    build: 
      dockerfile: Dockerfile
    container_name: provider-service
    ports:
      - 3002:3002
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/provider_service_db
      - DB_HOST=database
      - POSTGRES_DB=provider_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  database:
    image: postgres:14.1-alpine
    restart: always
    container_name: provider-service-database
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=provider_service_db
volumes:
  db:
    driver: local