@account_id = 86fd29fc-eb3e-48c4-a6e6-7fd50b92d131

# @name providerPost
post http://localhost:3002/api/v1/provider
X-ACCOUNT-ID : {{account_id}}
content-type : application/json

{
    "name": "vscreseame",
    "title": "testtile",
    "phoneNumber": "1234567890"
}

###

@provider_id = {{providerPost.response.body.$.result.$.id}}

patch http://localhost:3002/api/v1/provider/{{provider_id}}
X-ACCOUNT-ID : {{account_id}}
content-type : application/json

{
    "description" : "updated description"
}