@account_id = 86fd29fc-eb3e-48c4-a6e6-7fd50b92d131
@provider_id = 1013

post http://localhost:3001/api/v1/provider
X-ACCOUNT-ID : {{account_id}}
content-type : application/json

{
    "name": "vscrestname",
    "title": "testtile",
    "phoneNumber": "1234567890"
}

###

post http://localhost:3001/api/v1/provider/{{provider_id}}/item
X-ACCOUNT-ID : {{account_id}}
content-type : application/json

{
    "title" : "testtitle11",
    "priceCents" : 1200,
    "subItems" : [
        {
            "title" :"itemtesttitle",
            "priceCents" : 1400
        },
        {
            "title" :"itemtesttitle2",
            "priceCents" : 1200
        },
        {
            "title" :"itemtesttitle3",
            "priceCents" : 1300
        }
    ]
}

###

@item_id = 36

put http://localhost:3001/api/v1/provider/{{provider_id}}/item/{{item_id}}
X-ACCOUNT-ID : {{account_id}}
content-type : application/json

{
    "title" : "updatedTitle2",
    "priceCents" : 100,
    "status" : "cancelled"
}