/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.provider.controller;

import com.provider.model.ItemRequestModel;
import com.provider.model.ItemReturnModel;
import com.provider.model.ItemUpdateRequestModel;
import com.provider.model.ItemUpdateReturnModel;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.UUID;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
public interface ItemApi {

  /**
   * PUT /api/v1/provider/{provider-id}/item/{item-id} Update item
   *
   * @param X_ACCOUNT_ID (required)
   * @param providerId (required)
   * @param itemId (required)
   * @param itemUpdateRequestModel Item to be updated (required)
   * @return updated (status code 200) or Bad request! (status code 400)
   */
  @RequestMapping(
      method = RequestMethod.PUT,
      value = "/api/v1/provider/{provider-id}/item/{item-id}",
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<ItemUpdateReturnModel> apiV1ProviderProviderIdItemItemIdPut(
      @NotNull @RequestHeader(value = "X-ACCOUNT-ID", required = true) UUID X_ACCOUNT_ID,
      @PathVariable("provider-id") Long providerId,
      @PathVariable("item-id") Long itemId,
      @Valid @RequestBody ItemUpdateRequestModel itemUpdateRequestModel)
      throws Exception;

  /**
   * POST /api/v1/provider/{provider-id}/item Add item
   *
   * @param X_ACCOUNT_ID (required)
   * @param providerId (required)
   * @param itemRequestModel Item to be added (required)
   * @return Created (status code 201) or Bad request! (status code 400)
   */
  @RequestMapping(
      method = RequestMethod.POST,
      value = "/api/v1/provider/{provider-id}/item",
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<ItemReturnModel> apiV1ProviderProviderIdItemPost(
      @NotNull @RequestHeader(value = "X-ACCOUNT-ID", required = true) UUID X_ACCOUNT_ID,
      @PathVariable("provider-id") Long providerId,
      @Valid @RequestBody ItemRequestModel itemRequestModel)
      throws Exception;
}
