/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.provider.controller;

import com.provider.model.OrderByEnum;
import com.provider.model.OrderEnum;
import com.provider.model.TitleGetReturnModel;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.UUID;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
public interface TitleApi {

  /**
   * GET /api/v1/title/search Get all by title
   *
   * @param X_ACCOUNT_ID (required)
   * @param query (required)
   * @param page (required)
   * @param orderBy (optional)
   * @param order (optional)
   * @param pageSize (optional)
   * @return fetched (status code 200) or No content! (status code 204) or Bad request! (status code
   *     400)
   */
  @RequestMapping(
      method = RequestMethod.GET,
      value = "/api/v1/title/search",
      produces = {"application/json"})
  ResponseEntity<TitleGetReturnModel> getAllByTitle(
      @NotNull @RequestHeader(value = "X-ACCOUNT-ID", required = true) UUID X_ACCOUNT_ID,
      @NotNull @Valid @RequestParam(value = "query", required = true) String query,
      @NotNull @Valid @RequestParam(value = "page", required = true) Integer page,
      @Valid @RequestParam(value = "order-by", required = false) OrderByEnum orderBy,
      @Valid @RequestParam(value = "order", required = false) OrderEnum order,
      @Min(20) @Max(100) @Valid @RequestParam(value = "page-size", required = false)
          Integer pageSize)
      throws Exception;
}
